apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common
  template:
    metadata:
      labels:
        app: common
    spec:
      containers:
        - name: common
          image: 277707114689.dkr.ecr.ap-northeast-2.amazonaws.com/tama-api/common:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5005