name: CICD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      ECR_REGISTRY: 277707114689.dkr.ecr.ap-northeast-2.amazonaws.com
      IMAGE_NAME: tama-api/member
      CLUSTER_NAME: tama-api-cluster
      DEPLOYMENT_NAME: member-service
      CONTAINER_NAME: member
      K8S_NAMESPACE: default

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl (use aws eks update-kubeconfig)
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Deploy order
        if: contains(steps.changed-files.outputs.all_changed_files, 'order/')
        run: kubectl apply -f order/

      - name: Deploy item
        if: contains(steps.changed-files.outputs.all_changed_files, 'item/')
        run: kubectl apply -f item/

      - name: Deploy member
        if: contains(steps.changed-files.outputs.all_changed_files, 'member/')
        run: kubectl apply -f member/

      - name: Deploy common
        if: contains(steps.changed-files.outputs.all_changed_files, 'common/')
        run: kubectl apply -f common/

      - name: Deploy nginx
        if: contains(steps.changed-files.outputs.all_changed_files, 'nginx/')
        run: kubectl apply -f nginx/

      - name: Deploy zipkin
        if: contains(steps.changed-files.outputs.all_changed_files, 'zipkin/')
        run: kubectl apply -f zipkin/

      - name: Deploy elastic-search
        if: contains(steps.changed-files.outputs.all_changed_files, 'elastic-search/')
        run: kubectl apply -f elastic-search/

      - name: Deploy fluent-bit
        if: contains(steps.changed-files.outputs.all_changed_files, 'fluent-bit/')
        run: kubectl apply -f fluent-bit/